### ISSUE TITLE
Publish to apm?

### ISSUE THREAD

**Issue by maxim-lian** [nikitakit/hydrogen-python#1]
Not a great unexpected insight, but I don't see it there yet!

![image](https://user-images.githubusercontent.com/5635139/36997653-594e840a-2088-11e8-8e5e-ba5affbe7194.png)

**Comment by nikitakit** [comment]
I'm waiting on the next version of hydrogen to be out.

No point in pushing this plugin out to apm if you still need to install hydrogen master from github.

**Comment by kylebarron** [comment]
It's out now!
https://github.com/nteract/hydrogen/commit/2d5ad118d7e236921068888d482789e809a64a79

**Comment by nikitakit** [comment]
And now this plugin is out on npm as well!

Now it's time to let the bug reports roll in... I suspect there may be some issues, such as python2 compatibility.
