### ISSUE TITLE
Bug when sending function

### ISSUE THREAD

**Issue by kylebarron** [nikitakit/hydrogen-python#2]
Sorry to report a bug! Without this add-on installed, if I have my cursor at the end of the second line below, (at the place of the `|`) it'll send the rest of the function. With this installed, it appears that something is going awry and not sending to the ipython kernel correctly. It appears that the same error occurs when I select the 2nd through 4th lines. I'm hitting <kbd>cmd</kbd>+<kbd>enter</kbd> (`hydrogen:run`) in both instances.

```py
d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(|
    data=d,
    dtype=np.int8)
```
```
File "<ipython-input-19-8cb79410d243>", line 2
    data=d,
           ^
SyntaxError: unexpected EOF while parsing
```

**Comment by nikitakit** [comment]
Hopefully fixed now.

This is embarrassing, looks like I don't know how the Javascript string manipulation APIs work.
